import { StandardTableView, VerticalBox, HorizontalBox, Button } from "std-widgets.slint";

export global MainWindowAdapter {
    in property <[string]> titles;
    in property <[[StandardListViewItem]]> model;
}

export component MainWindow inherits Window {
    default-font-family: "Microsoft YaHei";
    title: "MonitorHosts";
    icon: @image-url("../icons/monitorhosts.png");
    min-width: 640px;
    min-height: 480px;
    background: white;
    preferred-width: 1024px;
    preferred-height: 768px;
    padding: 0px;

    in property <[string]> titles <=> MainWindowAdapter.titles;
    in property <[[StandardListViewItem]]> model <=> MainWindowAdapter.model;
    callback add-host();
    callback remove-host(int);
    callback config-host(int);
    callback clear-hosts();

    VerticalBox {
        padding: 0px;
        spacing: 0px;
        HorizontalBox {
            Button {
                text: "添加";
                horizontal-stretch: 0;
                clicked => { root.add-host(); }
            }
            Button {
                text: "删除";
                horizontal-stretch: 0;
                clicked => { root.remove-host(i-table-view.current-row); }
                enabled: (i-table-view.current-row >= 0) && (i-table-view.current-row < i-table-view.rows.length);
            }
            Button {
                text: "配置";
                horizontal-stretch: 0;
                clicked => { root.config-host(i-table-view.current-row); }
                enabled: (i-table-view.current-row >= 0) && (i-table-view.current-row < i-table-view.rows.length);
            }
            Button {
                text: "清空";
                horizontal-stretch: 0;
                clicked => { root.clear-hosts(); }
                enabled: i-table-view.rows.length > 0;
            }
            Rectangle {
                horizontal-stretch: 1;
            }
        }
        i-table-view := StandardTableView {
            columns: [
                { title: "主机名", horizontal_stretch: 1, min_width: 256px },
                { title: "Ping", horizontal_stretch: 0.1, min_width: 64px },
                { title: "HTTP", horizontal_stretch: 0.1, min_width: 64px },
                { title: "HTTPS", horizontal_stretch: 0.1, min_width: 64px },
                { title: "SSH", horizontal_stretch: 0.1, min_width: 64px },
                { title: "VNC", horizontal_stretch: 0.1, min_width: 64px },
                { title: "IPMI", horizontal_stretch: 0.1, min_width: 64px },
            ];
            rows: root.model;
        }
    }
}